name: py_cloud_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  auto_route: ^9.2.2
  built_value: ^8.9.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  generated:
    path: generated
  hooks_riverpod: ^2.5.2
  one_of: ^1.5.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  video_player: ^2.9.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
